name: ldk_node
description: A ready-to-go Lightning node library built using LDK and BDK.
version: 0.2.3-dev
homepage: https://github.com/LtbLightning/ldk-node-flutter

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.17.1
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_rust_bridge: ">2.0.0-dev.30 <= 2.0.0-dev.31"
  freezed_annotation: ^2.2.0
  meta: ^1.10.0
  uuid: ^4.3.3
  path_provider: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  ffigen: ^9.0.1
  freezed: ^2.4.7
  build_runner: ^2.4.8
  lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
