// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// Section: imports

use super::*;
use crate::api::node::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::transform_result_dco;
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_io!();

// Section: dart2rust

impl CstDecode<RustOpaqueNom<Node<SqliteStore>>> for usize {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> RustOpaqueNom<Node<SqliteStore>> {
        unsafe { decode_rust_opaque_nom(self as _) }
    }
}
impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> String {
        let vec: Vec<u8> = self.cst_decode();
        String::from_utf8(vec).unwrap()
    }
}
impl CstDecode<crate::api::types::Address> for wire_cst_address {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::Address {
        crate::api::types::Address {
            s: self.s.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::BalanceDetails> for wire_cst_balance_details {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::BalanceDetails {
        crate::api::types::BalanceDetails {
            total_onchain_balance_sats: self.total_onchain_balance_sats.cst_decode(),
            spendable_onchain_balance_sats: self.spendable_onchain_balance_sats.cst_decode(),
            total_lightning_balance_sats: self.total_lightning_balance_sats.cst_decode(),
            lightning_balances: self.lightning_balances.cst_decode(),
            pending_balances_from_channel_closures: self
                .pending_balances_from_channel_closures
                .cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::BestBlock> for wire_cst_best_block {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::BestBlock {
        crate::api::types::BestBlock {
            block_hash: self.block_hash.cst_decode(),
            height: self.height.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::Bolt11Invoice> for wire_cst_bolt_11_invoice {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::Bolt11Invoice {
        crate::api::types::Bolt11Invoice {
            signed_raw_invoice: self.signed_raw_invoice.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::Address> for *mut wire_cst_address {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::Address {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::Address>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::Bolt11Invoice> for *mut wire_cst_bolt_11_invoice {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::Bolt11Invoice {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::Bolt11Invoice>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::ChainDataSourceConfig>
    for *mut wire_cst_chain_data_source_config
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::ChainDataSourceConfig {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::ChainDataSourceConfig>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::ChannelConfig> for *mut wire_cst_channel_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::ChannelConfig {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::ChannelConfig>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::ChannelId> for *mut wire_cst_channel_id {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::ChannelId {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::ChannelId>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::ClosureReason> for *mut wire_cst_closure_reason {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::ClosureReason {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::ClosureReason>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::Config> for *mut wire_cst_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::Config {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::Config>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::EntropySourceConfig> for *mut wire_cst_entropy_source_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::EntropySourceConfig {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::EntropySourceConfig>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::Event> for *mut wire_cst_event {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::Event {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::Event>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::GossipSourceConfig> for *mut wire_cst_gossip_source_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::GossipSourceConfig {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::GossipSourceConfig>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::LiquiditySourceConfig> for *mut wire_cst_liquidity_source_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::LiquiditySourceConfig {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::LiquiditySourceConfig>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::MaxDustHTLCExposure> for *mut wire_cst_max_dust_htlc_exposure {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::MaxDustHTLCExposure {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::MaxDustHTLCExposure>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::node::MnemonicBase> for *mut wire_cst_mnemonic_base {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::node::MnemonicBase {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::node::MnemonicBase>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::node::NodeBase> for *mut wire_cst_node_base {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::node::NodeBase {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::node::NodeBase>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::OutPoint> for *mut wire_cst_out_point {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::OutPoint {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::OutPoint>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::PaymentDetails> for *mut wire_cst_payment_details {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PaymentDetails {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::PaymentDetails>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::PaymentFailureReason> for *mut i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PaymentFailureReason {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::PaymentFailureReason>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::PaymentHash> for *mut wire_cst_payment_hash {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PaymentHash {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::PaymentHash>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::PaymentPreimage> for *mut wire_cst_payment_preimage {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PaymentPreimage {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::PaymentPreimage>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::PaymentSecret> for *mut wire_cst_payment_secret {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PaymentSecret {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::PaymentSecret>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::PublicKey> for *mut wire_cst_public_key {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PublicKey {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::PublicKey>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::SocketAddress> for *mut wire_cst_socket_address {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::SocketAddress {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::SocketAddress>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::Txid> for *mut wire_cst_txid {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::Txid {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::Txid>::cst_decode(*wrap).into()
    }
}
impl CstDecode<u16> for *mut u16 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u16 {
        unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
    }
}
impl CstDecode<u32> for *mut u32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u32 {
        unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
    }
}
impl CstDecode<u64> for *mut u64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u64 {
        unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
    }
}
impl CstDecode<crate::api::types::UserChannelId> for *mut wire_cst_user_channel_id {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::UserChannelId {
        let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
        CstDecode::<crate::api::types::UserChannelId>::cst_decode(*wrap).into()
    }
}
impl CstDecode<crate::api::types::ChainDataSourceConfig> for wire_cst_chain_data_source_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::ChainDataSourceConfig {
        match self.tag {
            0 => {
                let ans = unsafe { self.kind.Esplora };
                crate::api::types::ChainDataSourceConfig::Esplora(ans.field0.cst_decode())
            }
            _ => unreachable!(),
        }
    }
}
impl CstDecode<crate::api::types::ChannelConfig> for wire_cst_channel_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::ChannelConfig {
        crate::api::types::ChannelConfig {
            forwarding_fee_proportional_millionths: self
                .forwarding_fee_proportional_millionths
                .cst_decode(),
            forwarding_fee_base_msat: self.forwarding_fee_base_msat.cst_decode(),
            cltv_expiry_delta: self.cltv_expiry_delta.cst_decode(),
            max_dust_htlc_exposure: self.max_dust_htlc_exposure.cst_decode(),
            force_close_avoidance_max_fee_satoshis: self
                .force_close_avoidance_max_fee_satoshis
                .cst_decode(),
            accept_underpaying_htlcs: self.accept_underpaying_htlcs.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::ChannelDetails> for wire_cst_channel_details {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::ChannelDetails {
        crate::api::types::ChannelDetails {
            channel_id: self.channel_id.cst_decode(),
            counterparty_node_id: self.counterparty_node_id.cst_decode(),
            funding_txo: self.funding_txo.cst_decode(),
            channel_value_sats: self.channel_value_sats.cst_decode(),
            unspendable_punishment_reserve: self.unspendable_punishment_reserve.cst_decode(),
            user_channel_id: self.user_channel_id.cst_decode(),
            feerate_sat_per_1000_weight: self.feerate_sat_per_1000_weight.cst_decode(),
            outbound_capacity_msat: self.outbound_capacity_msat.cst_decode(),
            inbound_capacity_msat: self.inbound_capacity_msat.cst_decode(),
            confirmations_required: self.confirmations_required.cst_decode(),
            confirmations: self.confirmations.cst_decode(),
            is_outbound: self.is_outbound.cst_decode(),
            is_channel_ready: self.is_channel_ready.cst_decode(),
            is_usable: self.is_usable.cst_decode(),
            is_public: self.is_public.cst_decode(),
            cltv_expiry_delta: self.cltv_expiry_delta.cst_decode(),
            counterparty_unspendable_punishment_reserve: self
                .counterparty_unspendable_punishment_reserve
                .cst_decode(),
            counterparty_outbound_htlc_minimum_msat: self
                .counterparty_outbound_htlc_minimum_msat
                .cst_decode(),
            counterparty_outbound_htlc_maximum_msat: self
                .counterparty_outbound_htlc_maximum_msat
                .cst_decode(),
            counterparty_forwarding_info_fee_base_msat: self
                .counterparty_forwarding_info_fee_base_msat
                .cst_decode(),
            counterparty_forwarding_info_fee_proportional_millionths: self
                .counterparty_forwarding_info_fee_proportional_millionths
                .cst_decode(),
            counterparty_forwarding_info_cltv_expiry_delta: self
                .counterparty_forwarding_info_cltv_expiry_delta
                .cst_decode(),
            next_outbound_htlc_limit_msat: self.next_outbound_htlc_limit_msat.cst_decode(),
            next_outbound_htlc_minimum_msat: self.next_outbound_htlc_minimum_msat.cst_decode(),
            force_close_spend_delay: self.force_close_spend_delay.cst_decode(),
            inbound_htlc_minimum_msat: self.inbound_htlc_minimum_msat.cst_decode(),
            inbound_htlc_maximum_msat: self.inbound_htlc_maximum_msat.cst_decode(),
            config: self.config.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::ChannelId> for wire_cst_channel_id {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::ChannelId {
        crate::api::types::ChannelId {
            data: self.data.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::ClosureReason> for wire_cst_closure_reason {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::ClosureReason {
        match self.tag {
            0 => {
                let ans = unsafe { self.kind.CounterpartyForceClosed };
                crate::api::types::ClosureReason::CounterpartyForceClosed {
                    peer_msg: ans.peer_msg.cst_decode(),
                }
            }
            1 => crate::api::types::ClosureReason::HolderForceClosed,
            2 => crate::api::types::ClosureReason::CooperativeClosure,
            3 => crate::api::types::ClosureReason::CommitmentTxConfirmed,
            4 => crate::api::types::ClosureReason::FundingTimedOut,
            5 => {
                let ans = unsafe { self.kind.ProcessingError };
                crate::api::types::ClosureReason::ProcessingError {
                    err: ans.err.cst_decode(),
                }
            }
            6 => crate::api::types::ClosureReason::DisconnectedPeer,
            7 => crate::api::types::ClosureReason::OutdatedChannelManager,
            8 => crate::api::types::ClosureReason::CounterpartyCoopClosedUnfundedChannel,
            9 => crate::api::types::ClosureReason::FundingBatchClosure,
            _ => unreachable!(),
        }
    }
}
impl CstDecode<crate::api::types::Config> for wire_cst_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::Config {
        crate::api::types::Config {
            storage_dir_path: self.storage_dir_path.cst_decode(),
            log_dir_path: self.log_dir_path.cst_decode(),
            network: self.network.cst_decode(),
            listening_addresses: self.listening_addresses.cst_decode(),
            default_cltv_expiry_delta: self.default_cltv_expiry_delta.cst_decode(),
            onchain_wallet_sync_interval_secs: self.onchain_wallet_sync_interval_secs.cst_decode(),
            wallet_sync_interval_secs: self.wallet_sync_interval_secs.cst_decode(),
            fee_rate_cache_update_interval_secs: self
                .fee_rate_cache_update_interval_secs
                .cst_decode(),
            trusted_peers_0conf: self.trusted_peers_0conf.cst_decode(),
            probing_liquidity_limit_multiplier: self
                .probing_liquidity_limit_multiplier
                .cst_decode(),
            log_level: self.log_level.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::EntropySourceConfig> for wire_cst_entropy_source_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::EntropySourceConfig {
        match self.tag {
            0 => {
                let ans = unsafe { self.kind.SeedFile };
                crate::api::types::EntropySourceConfig::SeedFile(ans.field0.cst_decode())
            }
            1 => {
                let ans = unsafe { self.kind.SeedBytes };
                crate::api::types::EntropySourceConfig::SeedBytes(ans.field0.cst_decode())
            }
            2 => {
                let ans = unsafe { self.kind.Bip39Mnemonic };
                crate::api::types::EntropySourceConfig::Bip39Mnemonic {
                    mnemonic: ans.mnemonic.cst_decode(),
                    passphrase: ans.passphrase.cst_decode(),
                }
            }
            _ => unreachable!(),
        }
    }
}
impl CstDecode<crate::api::types::Event> for wire_cst_event {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::Event {
        match self.tag {
            0 => {
                let ans = unsafe { self.kind.PaymentSuccessful };
                crate::api::types::Event::PaymentSuccessful {
                    payment_hash: ans.payment_hash.cst_decode(),
                    fee_paid_msat: ans.fee_paid_msat.cst_decode(),
                }
            }
            1 => {
                let ans = unsafe { self.kind.PaymentFailed };
                crate::api::types::Event::PaymentFailed {
                    payment_hash: ans.payment_hash.cst_decode(),
                    reason: ans.reason.cst_decode(),
                }
            }
            2 => {
                let ans = unsafe { self.kind.PaymentReceived };
                crate::api::types::Event::PaymentReceived {
                    payment_hash: ans.payment_hash.cst_decode(),
                    amount_msat: ans.amount_msat.cst_decode(),
                }
            }
            3 => {
                let ans = unsafe { self.kind.ChannelPending };
                crate::api::types::Event::ChannelPending {
                    channel_id: ans.channel_id.cst_decode(),
                    user_channel_id: ans.user_channel_id.cst_decode(),
                    former_temporary_channel_id: ans.former_temporary_channel_id.cst_decode(),
                    counterparty_node_id: ans.counterparty_node_id.cst_decode(),
                    funding_txo: ans.funding_txo.cst_decode(),
                }
            }
            4 => {
                let ans = unsafe { self.kind.ChannelReady };
                crate::api::types::Event::ChannelReady {
                    channel_id: ans.channel_id.cst_decode(),
                    user_channel_id: ans.user_channel_id.cst_decode(),
                    counterparty_node_id: ans.counterparty_node_id.cst_decode(),
                }
            }
            5 => {
                let ans = unsafe { self.kind.ChannelClosed };
                crate::api::types::Event::ChannelClosed {
                    channel_id: ans.channel_id.cst_decode(),
                    user_channel_id: ans.user_channel_id.cst_decode(),
                    counterparty_node_id: ans.counterparty_node_id.cst_decode(),
                    reason: ans.reason.cst_decode(),
                }
            }
            _ => unreachable!(),
        }
    }
}
impl CstDecode<crate::api::types::GossipSourceConfig> for wire_cst_gossip_source_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::GossipSourceConfig {
        match self.tag {
            0 => crate::api::types::GossipSourceConfig::P2PNetwork,
            1 => {
                let ans = unsafe { self.kind.RapidGossipSync };
                crate::api::types::GossipSourceConfig::RapidGossipSync(ans.field0.cst_decode())
            }
            _ => unreachable!(),
        }
    }
}
impl CstDecode<crate::api::types::LightningBalance> for wire_cst_lightning_balance {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::LightningBalance {
        match self.tag {
            0 => {
                let ans = unsafe { self.kind.ClaimableOnChannelClose };
                crate::api::types::LightningBalance::ClaimableOnChannelClose {
                    channel_id: ans.channel_id.cst_decode(),
                    counterparty_node_id: ans.counterparty_node_id.cst_decode(),
                    amount_satoshis: ans.amount_satoshis.cst_decode(),
                }
            }
            1 => {
                let ans = unsafe { self.kind.ClaimableAwaitingConfirmations };
                crate::api::types::LightningBalance::ClaimableAwaitingConfirmations {
                    channel_id: ans.channel_id.cst_decode(),
                    counterparty_node_id: ans.counterparty_node_id.cst_decode(),
                    amount_satoshis: ans.amount_satoshis.cst_decode(),
                    confirmation_height: ans.confirmation_height.cst_decode(),
                }
            }
            2 => {
                let ans = unsafe { self.kind.ContentiousClaimable };
                crate::api::types::LightningBalance::ContentiousClaimable {
                    channel_id: ans.channel_id.cst_decode(),
                    counterparty_node_id: ans.counterparty_node_id.cst_decode(),
                    amount_satoshis: ans.amount_satoshis.cst_decode(),
                    timeout_height: ans.timeout_height.cst_decode(),
                    payment_hash: ans.payment_hash.cst_decode(),
                    payment_preimage: ans.payment_preimage.cst_decode(),
                }
            }
            3 => {
                let ans = unsafe { self.kind.MaybeTimeoutClaimableHTLC };
                crate::api::types::LightningBalance::MaybeTimeoutClaimableHTLC {
                    channel_id: ans.channel_id.cst_decode(),
                    counterparty_node_id: ans.counterparty_node_id.cst_decode(),
                    amount_satoshis: ans.amount_satoshis.cst_decode(),
                    claimable_height: ans.claimable_height.cst_decode(),
                    payment_hash: ans.payment_hash.cst_decode(),
                }
            }
            4 => {
                let ans = unsafe { self.kind.MaybePreimageClaimableHTLC };
                crate::api::types::LightningBalance::MaybePreimageClaimableHTLC {
                    channel_id: ans.channel_id.cst_decode(),
                    counterparty_node_id: ans.counterparty_node_id.cst_decode(),
                    amount_satoshis: ans.amount_satoshis.cst_decode(),
                    expiry_height: ans.expiry_height.cst_decode(),
                    payment_hash: ans.payment_hash.cst_decode(),
                }
            }
            5 => {
                let ans = unsafe { self.kind.CounterpartyRevokedOutputClaimable };
                crate::api::types::LightningBalance::CounterpartyRevokedOutputClaimable {
                    channel_id: ans.channel_id.cst_decode(),
                    counterparty_node_id: ans.counterparty_node_id.cst_decode(),
                    amount_satoshis: ans.amount_satoshis.cst_decode(),
                }
            }
            _ => unreachable!(),
        }
    }
}
impl CstDecode<crate::api::types::LiquiditySourceConfig> for wire_cst_liquidity_source_config {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::LiquiditySourceConfig {
        crate::api::types::LiquiditySourceConfig {
            lsps2_service: self.lsps2_service.cst_decode(),
        }
    }
}
impl CstDecode<Vec<crate::api::types::ChannelDetails>> for *mut wire_cst_list_channel_details {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<crate::api::types::ChannelDetails> {
        let vec = unsafe {
            let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
            flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
        };
        vec.into_iter().map(CstDecode::cst_decode).collect()
    }
}
impl CstDecode<Vec<crate::api::types::LightningBalance>> for *mut wire_cst_list_lightning_balance {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<crate::api::types::LightningBalance> {
        let vec = unsafe {
            let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
            flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
        };
        vec.into_iter().map(CstDecode::cst_decode).collect()
    }
}
impl CstDecode<Vec<crate::api::types::PaymentDetails>> for *mut wire_cst_list_payment_details {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<crate::api::types::PaymentDetails> {
        let vec = unsafe {
            let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
            flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
        };
        vec.into_iter().map(CstDecode::cst_decode).collect()
    }
}
impl CstDecode<Vec<crate::api::types::PeerDetails>> for *mut wire_cst_list_peer_details {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<crate::api::types::PeerDetails> {
        let vec = unsafe {
            let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
            flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
        };
        vec.into_iter().map(CstDecode::cst_decode).collect()
    }
}
impl CstDecode<Vec<crate::api::types::PendingSweepBalance>>
    for *mut wire_cst_list_pending_sweep_balance
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<crate::api::types::PendingSweepBalance> {
        let vec = unsafe {
            let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
            flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
        };
        vec.into_iter().map(CstDecode::cst_decode).collect()
    }
}
impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_loose {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<u8> {
        unsafe {
            let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
            flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
        }
    }
}
impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<u8> {
        unsafe {
            let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
            flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
        }
    }
}
impl CstDecode<Vec<crate::api::types::PublicKey>> for *mut wire_cst_list_public_key {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<crate::api::types::PublicKey> {
        let vec = unsafe {
            let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
            flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
        };
        vec.into_iter().map(CstDecode::cst_decode).collect()
    }
}
impl CstDecode<Vec<crate::api::types::SocketAddress>> for *mut wire_cst_list_socket_address {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> Vec<crate::api::types::SocketAddress> {
        let vec = unsafe {
            let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
            flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
        };
        vec.into_iter().map(CstDecode::cst_decode).collect()
    }
}
impl CstDecode<crate::api::types::MaxDustHTLCExposure> for wire_cst_max_dust_htlc_exposure {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::MaxDustHTLCExposure {
        match self.tag {
            0 => {
                let ans = unsafe { self.kind.FixedLimitMsat };
                crate::api::types::MaxDustHTLCExposure::FixedLimitMsat(ans.field0.cst_decode())
            }
            1 => {
                let ans = unsafe { self.kind.FeeRateMultiplier };
                crate::api::types::MaxDustHTLCExposure::FeeRateMultiplier(ans.field0.cst_decode())
            }
            _ => unreachable!(),
        }
    }
}
impl CstDecode<crate::api::node::MnemonicBase> for wire_cst_mnemonic_base {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::node::MnemonicBase {
        crate::api::node::MnemonicBase {
            seed_phrase: self.seed_phrase.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::node::NodeBase> for wire_cst_node_base {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::node::NodeBase {
        crate::api::node::NodeBase {
            ptr: self.ptr.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::NodeStatus> for wire_cst_node_status {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::NodeStatus {
        crate::api::types::NodeStatus {
            is_running: self.is_running.cst_decode(),
            is_listening: self.is_listening.cst_decode(),
            current_best_block: self.current_best_block.cst_decode(),
            latest_wallet_sync_timestamp: self.latest_wallet_sync_timestamp.cst_decode(),
            latest_onchain_wallet_sync_timestamp: self
                .latest_onchain_wallet_sync_timestamp
                .cst_decode(),
            latest_fee_rate_cache_update_timestamp: self
                .latest_fee_rate_cache_update_timestamp
                .cst_decode(),
            latest_rgs_snapshot_timestamp: self.latest_rgs_snapshot_timestamp.cst_decode(),
            latest_node_announcement_broadcast_timestamp: self
                .latest_node_announcement_broadcast_timestamp
                .cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::OutPoint> for wire_cst_out_point {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::OutPoint {
        crate::api::types::OutPoint {
            txid: self.txid.cst_decode(),
            vout: self.vout.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::PaymentDetails> for wire_cst_payment_details {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PaymentDetails {
        crate::api::types::PaymentDetails {
            hash: self.hash.cst_decode(),
            preimage: self.preimage.cst_decode(),
            secret: self.secret.cst_decode(),
            amount_msat: self.amount_msat.cst_decode(),
            direction: self.direction.cst_decode(),
            status: self.status.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::PaymentHash> for wire_cst_payment_hash {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PaymentHash {
        crate::api::types::PaymentHash {
            data: self.data.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::PaymentPreimage> for wire_cst_payment_preimage {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PaymentPreimage {
        crate::api::types::PaymentPreimage {
            data: self.data.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::PaymentSecret> for wire_cst_payment_secret {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PaymentSecret {
        crate::api::types::PaymentSecret {
            data: self.data.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::PeerDetails> for wire_cst_peer_details {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PeerDetails {
        crate::api::types::PeerDetails {
            node_id: self.node_id.cst_decode(),
            address: self.address.cst_decode(),
            is_connected: self.is_connected.cst_decode(),
        }
    }
}
impl CstDecode<crate::api::types::PendingSweepBalance> for wire_cst_pending_sweep_balance {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PendingSweepBalance {
        match self.tag {
            0 => {
                let ans = unsafe { self.kind.PendingBroadcast };
                crate::api::types::PendingSweepBalance::PendingBroadcast {
                    channel_id: ans.channel_id.cst_decode(),
                    amount_satoshis: ans.amount_satoshis.cst_decode(),
                }
            }
            1 => {
                let ans = unsafe { self.kind.BroadcastAwaitingConfirmation };
                crate::api::types::PendingSweepBalance::BroadcastAwaitingConfirmation {
                    channel_id: ans.channel_id.cst_decode(),
                    latest_broadcast_height: ans.latest_broadcast_height.cst_decode(),
                    latest_spending_txid: ans.latest_spending_txid.cst_decode(),
                    amount_satoshis: ans.amount_satoshis.cst_decode(),
                }
            }
            2 => {
                let ans = unsafe { self.kind.AwaitingThresholdConfirmations };
                crate::api::types::PendingSweepBalance::AwaitingThresholdConfirmations {
                    channel_id: ans.channel_id.cst_decode(),
                    latest_spending_txid: ans.latest_spending_txid.cst_decode(),
                    confirmation_hash: ans.confirmation_hash.cst_decode(),
                    confirmation_height: ans.confirmation_height.cst_decode(),
                    amount_satoshis: ans.amount_satoshis.cst_decode(),
                }
            }
            _ => unreachable!(),
        }
    }
}
impl CstDecode<crate::api::types::PublicKey> for wire_cst_public_key {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::PublicKey {
        crate::api::types::PublicKey {
            hex_code: self.hex_code.cst_decode(),
        }
    }
}
impl
    CstDecode<(
        crate::api::types::SocketAddress,
        crate::api::types::PublicKey,
        Option<String>,
    )> for wire_cst_record_socket_address_public_key_opt_string
{
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(
        self,
    ) -> (
        crate::api::types::SocketAddress,
        crate::api::types::PublicKey,
        Option<String>,
    ) {
        (
            self.field0.cst_decode(),
            self.field1.cst_decode(),
            self.field2.cst_decode(),
        )
    }
}
impl CstDecode<crate::api::types::SocketAddress> for wire_cst_socket_address {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::SocketAddress {
        match self.tag {
            0 => {
                let ans = unsafe { self.kind.TcpIpV4 };
                crate::api::types::SocketAddress::TcpIpV4 {
                    addr: ans.addr.cst_decode(),
                    port: ans.port.cst_decode(),
                }
            }
            1 => {
                let ans = unsafe { self.kind.TcpIpV6 };
                crate::api::types::SocketAddress::TcpIpV6 {
                    addr: ans.addr.cst_decode(),
                    port: ans.port.cst_decode(),
                }
            }
            2 => {
                let ans = unsafe { self.kind.OnionV2 };
                crate::api::types::SocketAddress::OnionV2(ans.field0.cst_decode())
            }
            3 => {
                let ans = unsafe { self.kind.OnionV3 };
                crate::api::types::SocketAddress::OnionV3 {
                    ed25519_pubkey: ans.ed25519_pubkey.cst_decode(),
                    checksum: ans.checksum.cst_decode(),
                    version: ans.version.cst_decode(),
                    port: ans.port.cst_decode(),
                }
            }
            4 => {
                let ans = unsafe { self.kind.Hostname };
                crate::api::types::SocketAddress::Hostname {
                    addr: ans.addr.cst_decode(),
                    port: ans.port.cst_decode(),
                }
            }
            _ => unreachable!(),
        }
    }
}
impl CstDecode<crate::api::types::Txid> for wire_cst_txid {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::Txid {
        crate::api::types::Txid {
            hash: self.hash.cst_decode(),
        }
    }
}
impl CstDecode<[u8; 12]> for *mut wire_cst_list_prim_u_8_strict {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> [u8; 12] {
        let vec: Vec<u8> = self.cst_decode();
        flutter_rust_bridge::for_generated::from_vec_to_array(vec)
    }
}
impl CstDecode<[u8; 16]> for *mut wire_cst_list_prim_u_8_strict {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> [u8; 16] {
        let vec: Vec<u8> = self.cst_decode();
        flutter_rust_bridge::for_generated::from_vec_to_array(vec)
    }
}
impl CstDecode<[u8; 32]> for *mut wire_cst_list_prim_u_8_strict {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> [u8; 32] {
        let vec: Vec<u8> = self.cst_decode();
        flutter_rust_bridge::for_generated::from_vec_to_array(vec)
    }
}
impl CstDecode<[u8; 4]> for *mut wire_cst_list_prim_u_8_strict {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> [u8; 4] {
        let vec: Vec<u8> = self.cst_decode();
        flutter_rust_bridge::for_generated::from_vec_to_array(vec)
    }
}
impl CstDecode<[u8; 64]> for *mut wire_cst_list_prim_u_8_strict {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> [u8; 64] {
        let vec: Vec<u8> = self.cst_decode();
        flutter_rust_bridge::for_generated::from_vec_to_array(vec)
    }
}
impl CstDecode<crate::api::types::UserChannelId> for wire_cst_user_channel_id {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::types::UserChannelId {
        crate::api::types::UserChannelId {
            data: self.data.cst_decode(),
        }
    }
}
impl NewWithNullPtr for wire_cst_address {
    fn new_with_null_ptr() -> Self {
        Self {
            s: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_address {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_balance_details {
    fn new_with_null_ptr() -> Self {
        Self {
            total_onchain_balance_sats: Default::default(),
            spendable_onchain_balance_sats: Default::default(),
            total_lightning_balance_sats: Default::default(),
            lightning_balances: core::ptr::null_mut(),
            pending_balances_from_channel_closures: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_balance_details {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_best_block {
    fn new_with_null_ptr() -> Self {
        Self {
            block_hash: core::ptr::null_mut(),
            height: Default::default(),
        }
    }
}
impl Default for wire_cst_best_block {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_bolt_11_invoice {
    fn new_with_null_ptr() -> Self {
        Self {
            signed_raw_invoice: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_bolt_11_invoice {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_chain_data_source_config {
    fn new_with_null_ptr() -> Self {
        Self {
            tag: -1,
            kind: ChainDataSourceConfigKind { nil__: () },
        }
    }
}
impl Default for wire_cst_chain_data_source_config {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_channel_config {
    fn new_with_null_ptr() -> Self {
        Self {
            forwarding_fee_proportional_millionths: Default::default(),
            forwarding_fee_base_msat: Default::default(),
            cltv_expiry_delta: Default::default(),
            max_dust_htlc_exposure: core::ptr::null_mut(),
            force_close_avoidance_max_fee_satoshis: Default::default(),
            accept_underpaying_htlcs: Default::default(),
        }
    }
}
impl Default for wire_cst_channel_config {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_channel_details {
    fn new_with_null_ptr() -> Self {
        Self {
            channel_id: Default::default(),
            counterparty_node_id: Default::default(),
            funding_txo: core::ptr::null_mut(),
            channel_value_sats: Default::default(),
            unspendable_punishment_reserve: core::ptr::null_mut(),
            user_channel_id: Default::default(),
            feerate_sat_per_1000_weight: Default::default(),
            outbound_capacity_msat: Default::default(),
            inbound_capacity_msat: Default::default(),
            confirmations_required: core::ptr::null_mut(),
            confirmations: core::ptr::null_mut(),
            is_outbound: Default::default(),
            is_channel_ready: Default::default(),
            is_usable: Default::default(),
            is_public: Default::default(),
            cltv_expiry_delta: core::ptr::null_mut(),
            counterparty_unspendable_punishment_reserve: Default::default(),
            counterparty_outbound_htlc_minimum_msat: core::ptr::null_mut(),
            counterparty_outbound_htlc_maximum_msat: core::ptr::null_mut(),
            counterparty_forwarding_info_fee_base_msat: core::ptr::null_mut(),
            counterparty_forwarding_info_fee_proportional_millionths: core::ptr::null_mut(),
            counterparty_forwarding_info_cltv_expiry_delta: core::ptr::null_mut(),
            next_outbound_htlc_limit_msat: Default::default(),
            next_outbound_htlc_minimum_msat: Default::default(),
            force_close_spend_delay: core::ptr::null_mut(),
            inbound_htlc_minimum_msat: Default::default(),
            inbound_htlc_maximum_msat: core::ptr::null_mut(),
            config: Default::default(),
        }
    }
}
impl Default for wire_cst_channel_details {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_channel_id {
    fn new_with_null_ptr() -> Self {
        Self {
            data: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_channel_id {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_closure_reason {
    fn new_with_null_ptr() -> Self {
        Self {
            tag: -1,
            kind: ClosureReasonKind { nil__: () },
        }
    }
}
impl Default for wire_cst_closure_reason {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_config {
    fn new_with_null_ptr() -> Self {
        Self {
            storage_dir_path: core::ptr::null_mut(),
            log_dir_path: core::ptr::null_mut(),
            network: Default::default(),
            listening_addresses: core::ptr::null_mut(),
            default_cltv_expiry_delta: Default::default(),
            onchain_wallet_sync_interval_secs: Default::default(),
            wallet_sync_interval_secs: Default::default(),
            fee_rate_cache_update_interval_secs: Default::default(),
            trusted_peers_0conf: core::ptr::null_mut(),
            probing_liquidity_limit_multiplier: Default::default(),
            log_level: Default::default(),
        }
    }
}
impl Default for wire_cst_config {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_entropy_source_config {
    fn new_with_null_ptr() -> Self {
        Self {
            tag: -1,
            kind: EntropySourceConfigKind { nil__: () },
        }
    }
}
impl Default for wire_cst_entropy_source_config {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_event {
    fn new_with_null_ptr() -> Self {
        Self {
            tag: -1,
            kind: EventKind { nil__: () },
        }
    }
}
impl Default for wire_cst_event {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_gossip_source_config {
    fn new_with_null_ptr() -> Self {
        Self {
            tag: -1,
            kind: GossipSourceConfigKind { nil__: () },
        }
    }
}
impl Default for wire_cst_gossip_source_config {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_lightning_balance {
    fn new_with_null_ptr() -> Self {
        Self {
            tag: -1,
            kind: LightningBalanceKind { nil__: () },
        }
    }
}
impl Default for wire_cst_lightning_balance {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_liquidity_source_config {
    fn new_with_null_ptr() -> Self {
        Self {
            lsps2_service: Default::default(),
        }
    }
}
impl Default for wire_cst_liquidity_source_config {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_max_dust_htlc_exposure {
    fn new_with_null_ptr() -> Self {
        Self {
            tag: -1,
            kind: MaxDustHTLCExposureKind { nil__: () },
        }
    }
}
impl Default for wire_cst_max_dust_htlc_exposure {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_mnemonic_base {
    fn new_with_null_ptr() -> Self {
        Self {
            seed_phrase: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_mnemonic_base {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_node_base {
    fn new_with_null_ptr() -> Self {
        Self {
            ptr: Default::default(),
        }
    }
}
impl Default for wire_cst_node_base {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_node_status {
    fn new_with_null_ptr() -> Self {
        Self {
            is_running: Default::default(),
            is_listening: Default::default(),
            current_best_block: Default::default(),
            latest_wallet_sync_timestamp: core::ptr::null_mut(),
            latest_onchain_wallet_sync_timestamp: core::ptr::null_mut(),
            latest_fee_rate_cache_update_timestamp: core::ptr::null_mut(),
            latest_rgs_snapshot_timestamp: core::ptr::null_mut(),
            latest_node_announcement_broadcast_timestamp: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_node_status {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_out_point {
    fn new_with_null_ptr() -> Self {
        Self {
            txid: Default::default(),
            vout: Default::default(),
        }
    }
}
impl Default for wire_cst_out_point {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_payment_details {
    fn new_with_null_ptr() -> Self {
        Self {
            hash: Default::default(),
            preimage: core::ptr::null_mut(),
            secret: core::ptr::null_mut(),
            amount_msat: core::ptr::null_mut(),
            direction: Default::default(),
            status: Default::default(),
        }
    }
}
impl Default for wire_cst_payment_details {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_payment_hash {
    fn new_with_null_ptr() -> Self {
        Self {
            data: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_payment_hash {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_payment_preimage {
    fn new_with_null_ptr() -> Self {
        Self {
            data: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_payment_preimage {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_payment_secret {
    fn new_with_null_ptr() -> Self {
        Self {
            data: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_payment_secret {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_peer_details {
    fn new_with_null_ptr() -> Self {
        Self {
            node_id: Default::default(),
            address: Default::default(),
            is_connected: Default::default(),
        }
    }
}
impl Default for wire_cst_peer_details {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_pending_sweep_balance {
    fn new_with_null_ptr() -> Self {
        Self {
            tag: -1,
            kind: PendingSweepBalanceKind { nil__: () },
        }
    }
}
impl Default for wire_cst_pending_sweep_balance {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_public_key {
    fn new_with_null_ptr() -> Self {
        Self {
            hex_code: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_public_key {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_record_socket_address_public_key_opt_string {
    fn new_with_null_ptr() -> Self {
        Self {
            field0: Default::default(),
            field1: Default::default(),
            field2: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_record_socket_address_public_key_opt_string {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_socket_address {
    fn new_with_null_ptr() -> Self {
        Self {
            tag: -1,
            kind: SocketAddressKind { nil__: () },
        }
    }
}
impl Default for wire_cst_socket_address {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_txid {
    fn new_with_null_ptr() -> Self {
        Self {
            hash: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_txid {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}
impl NewWithNullPtr for wire_cst_user_channel_id {
    fn new_with_null_ptr() -> Self {
        Self {
            data: core::ptr::null_mut(),
        }
    }
}
impl Default for wire_cst_user_channel_id {
    fn default() -> Self {
        Self::new_with_null_ptr()
    }
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_MnemonicBase_generate(port_: i64) {
    wire_MnemonicBase_generate_impl(port_)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_close_channel(
    port_: i64,
    that: *mut wire_cst_node_base,
    user_channel_id: *mut wire_cst_user_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
) {
    wire_NodeBase_close_channel_impl(port_, that, user_channel_id, counterparty_node_id)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_config(port_: i64, that: *mut wire_cst_node_base) {
    wire_NodeBase_config_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_connect(
    port_: i64,
    that: *mut wire_cst_node_base,
    node_id: *mut wire_cst_public_key,
    address: *mut wire_cst_socket_address,
    persist: bool,
) {
    wire_NodeBase_connect_impl(port_, that, node_id, address, persist)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_connect_open_channel(
    port_: i64,
    that: *mut wire_cst_node_base,
    address: *mut wire_cst_socket_address,
    node_id: *mut wire_cst_public_key,
    channel_amount_sats: u64,
    push_to_counterparty_msat: *mut u64,
    announce_channel: bool,
    channel_config: *mut wire_cst_channel_config,
) {
    wire_NodeBase_connect_open_channel_impl(
        port_,
        that,
        address,
        node_id,
        channel_amount_sats,
        push_to_counterparty_msat,
        announce_channel,
        channel_config,
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_disconnect(
    port_: i64,
    that: *mut wire_cst_node_base,
    counterparty_node_id: *mut wire_cst_public_key,
) {
    wire_NodeBase_disconnect_impl(port_, that, counterparty_node_id)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_event_handled(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_event_handled_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_list_balances(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_list_balances_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_list_channels(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_list_channels_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_list_payments(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_list_payments_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_list_payments_with_filter(
    port_: i64,
    that: *mut wire_cst_node_base,
    payment_direction: i32,
) {
    wire_NodeBase_list_payments_with_filter_impl(port_, that, payment_direction)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_list_peers(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_list_peers_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_listening_addresses(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_listening_addresses_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_new_onchain_address(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_new_onchain_address_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_next_event(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_next_event_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_next_event_async(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_next_event_async_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_node_id(port_: i64, that: *mut wire_cst_node_base) {
    wire_NodeBase_node_id_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_payment(
    port_: i64,
    that: *mut wire_cst_node_base,
    payment_hash: *mut wire_cst_payment_hash,
) {
    wire_NodeBase_payment_impl(port_, that, payment_hash)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_receive_payment(
    port_: i64,
    that: *mut wire_cst_node_base,
    amount_msat: u64,
    description: *mut wire_cst_list_prim_u_8_strict,
    expiry_secs: u32,
) {
    wire_NodeBase_receive_payment_impl(port_, that, amount_msat, description, expiry_secs)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_receive_payment_via_jit_channel(
    port_: i64,
    that: *mut wire_cst_node_base,
    amount_msat: u64,
    description: *mut wire_cst_list_prim_u_8_strict,
    expiry_secs: u32,
    max_total_lsp_fee_limit_msat: *mut u64,
) {
    wire_NodeBase_receive_payment_via_jit_channel_impl(
        port_,
        that,
        amount_msat,
        description,
        expiry_secs,
        max_total_lsp_fee_limit_msat,
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_receive_variable_amount_payment(
    port_: i64,
    that: *mut wire_cst_node_base,
    description: *mut wire_cst_list_prim_u_8_strict,
    expiry_secs: u32,
) {
    wire_NodeBase_receive_variable_amount_payment_impl(port_, that, description, expiry_secs)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_receive_variable_amount_payment_via_jit_channel(
    port_: i64,
    that: *mut wire_cst_node_base,
    description: *mut wire_cst_list_prim_u_8_strict,
    expiry_secs: u32,
    max_proportional_lsp_fee_limit_ppm_msat: *mut u64,
) {
    wire_NodeBase_receive_variable_amount_payment_via_jit_channel_impl(
        port_,
        that,
        description,
        expiry_secs,
        max_proportional_lsp_fee_limit_ppm_msat,
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_remove_payment(
    port_: i64,
    that: *mut wire_cst_node_base,
    payment_hash: *mut wire_cst_payment_hash,
) {
    wire_NodeBase_remove_payment_impl(port_, that, payment_hash)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_send_all_to_onchain_address(
    port_: i64,
    that: *mut wire_cst_node_base,
    address: *mut wire_cst_address,
) {
    wire_NodeBase_send_all_to_onchain_address_impl(port_, that, address)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_send_payment(
    port_: i64,
    that: *mut wire_cst_node_base,
    invoice: *mut wire_cst_bolt_11_invoice,
) {
    wire_NodeBase_send_payment_impl(port_, that, invoice)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_send_payment_probes(
    port_: i64,
    that: *mut wire_cst_node_base,
    invoice: *mut wire_cst_bolt_11_invoice,
) {
    wire_NodeBase_send_payment_probes_impl(port_, that, invoice)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_send_payment_probes_using_amount(
    port_: i64,
    that: *mut wire_cst_node_base,
    invoice: *mut wire_cst_bolt_11_invoice,
    amount_msat: u64,
) {
    wire_NodeBase_send_payment_probes_using_amount_impl(port_, that, invoice, amount_msat)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_send_payment_using_amount(
    port_: i64,
    that: *mut wire_cst_node_base,
    invoice: *mut wire_cst_bolt_11_invoice,
    amount_msat: u64,
) {
    wire_NodeBase_send_payment_using_amount_impl(port_, that, invoice, amount_msat)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_send_spontaneous_payment(
    port_: i64,
    that: *mut wire_cst_node_base,
    amount_msat: u64,
    node_id: *mut wire_cst_public_key,
) {
    wire_NodeBase_send_spontaneous_payment_impl(port_, that, amount_msat, node_id)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_send_spontaneous_payment_probes(
    port_: i64,
    that: *mut wire_cst_node_base,
    amount_msat: u64,
    node_id: *mut wire_cst_public_key,
) {
    wire_NodeBase_send_spontaneous_payment_probes_impl(port_, that, amount_msat, node_id)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_send_to_onchain_address(
    port_: i64,
    that: *mut wire_cst_node_base,
    address: *mut wire_cst_address,
    amount_sats: u64,
) {
    wire_NodeBase_send_to_onchain_address_impl(port_, that, address, amount_sats)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_sign_message(
    port_: i64,
    that: *mut wire_cst_node_base,
    msg: *mut wire_cst_list_prim_u_8_loose,
) {
    wire_NodeBase_sign_message_impl(port_, that, msg)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_start(port_: i64, that: *mut wire_cst_node_base) {
    wire_NodeBase_start_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_status(port_: i64, that: *mut wire_cst_node_base) {
    wire_NodeBase_status_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_stop(port_: i64, that: *mut wire_cst_node_base) {
    wire_NodeBase_stop_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_sync_wallets(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_sync_wallets_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_update_channel_config(
    port_: i64,
    that: *mut wire_cst_node_base,
    user_channel_id: *mut wire_cst_user_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
    channel_config: *mut wire_cst_channel_config,
) {
    wire_NodeBase_update_channel_config_impl(
        port_,
        that,
        user_channel_id,
        counterparty_node_id,
        channel_config,
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_verify_signature(
    port_: i64,
    that: *mut wire_cst_node_base,
    msg: *mut wire_cst_list_prim_u_8_loose,
    sig: *mut wire_cst_list_prim_u_8_strict,
    pkey: *mut wire_cst_public_key,
) {
    wire_NodeBase_verify_signature_impl(port_, that, msg, sig, pkey)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_NodeBase_wait_next_event(
    port_: i64,
    that: *mut wire_cst_node_base,
) {
    wire_NodeBase_wait_next_event_impl(port_, that)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_wire_finalize_builder(
    port_: i64,
    config: *mut wire_cst_config,
    chain_data_source_config: *mut wire_cst_chain_data_source_config,
    entropy_source_config: *mut wire_cst_entropy_source_config,
    gossip_source_config: *mut wire_cst_gossip_source_config,
    liquidity_source_config: *mut wire_cst_liquidity_source_config,
) {
    wire_finalize_builder_impl(
        port_,
        config,
        chain_data_source_config,
        entropy_source_config,
        gossip_source_config,
        liquidity_source_config,
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_rust_arc_increment_strong_count_RustOpaque_NodeSqliteStore(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<Node<SqliteStore>>::increment_strong_count(ptr as _);
    }
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_rust_arc_decrement_strong_count_RustOpaque_NodeSqliteStore(
    ptr: *const std::ffi::c_void,
) {
    unsafe {
        StdArc::<Node<SqliteStore>>::decrement_strong_count(ptr as _);
    }
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_address() -> *mut wire_cst_address {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_address::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_bolt_11_invoice(
) -> *mut wire_cst_bolt_11_invoice {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_bolt_11_invoice::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_chain_data_source_config(
) -> *mut wire_cst_chain_data_source_config {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_chain_data_source_config::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_channel_config(
) -> *mut wire_cst_channel_config {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_channel_config::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_channel_id() -> *mut wire_cst_channel_id {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_channel_id::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_closure_reason(
) -> *mut wire_cst_closure_reason {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_closure_reason::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_config() -> *mut wire_cst_config {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_config::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_entropy_source_config(
) -> *mut wire_cst_entropy_source_config {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_entropy_source_config::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_event() -> *mut wire_cst_event {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_event::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_gossip_source_config(
) -> *mut wire_cst_gossip_source_config {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_gossip_source_config::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_liquidity_source_config(
) -> *mut wire_cst_liquidity_source_config {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_liquidity_source_config::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_max_dust_htlc_exposure(
) -> *mut wire_cst_max_dust_htlc_exposure {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_max_dust_htlc_exposure::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_mnemonic_base() -> *mut wire_cst_mnemonic_base
{
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_mnemonic_base::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_node_base() -> *mut wire_cst_node_base {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_node_base::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_out_point() -> *mut wire_cst_out_point {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_out_point::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_payment_details(
) -> *mut wire_cst_payment_details {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_payment_details::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_payment_failure_reason(
    value: i32,
) -> *mut i32 {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_payment_hash() -> *mut wire_cst_payment_hash {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_payment_hash::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_payment_preimage(
) -> *mut wire_cst_payment_preimage {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_payment_preimage::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_payment_secret(
) -> *mut wire_cst_payment_secret {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_payment_secret::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_public_key() -> *mut wire_cst_public_key {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_public_key::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_socket_address(
) -> *mut wire_cst_socket_address {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_socket_address::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_txid() -> *mut wire_cst_txid {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wire_cst_txid::new_with_null_ptr())
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_u_16(value: u16) -> *mut u16 {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_u_32(value: u32) -> *mut u32 {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_u_64(value: u64) -> *mut u64 {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_box_autoadd_user_channel_id(
) -> *mut wire_cst_user_channel_id {
    flutter_rust_bridge::for_generated::new_leak_box_ptr(
        wire_cst_user_channel_id::new_with_null_ptr(),
    )
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_list_channel_details(
    len: i32,
) -> *mut wire_cst_list_channel_details {
    let wrap = wire_cst_list_channel_details {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
            <wire_cst_channel_details>::new_with_null_ptr(),
            len,
        ),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_list_lightning_balance(
    len: i32,
) -> *mut wire_cst_list_lightning_balance {
    let wrap = wire_cst_list_lightning_balance {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
            <wire_cst_lightning_balance>::new_with_null_ptr(),
            len,
        ),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_list_payment_details(
    len: i32,
) -> *mut wire_cst_list_payment_details {
    let wrap = wire_cst_list_payment_details {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
            <wire_cst_payment_details>::new_with_null_ptr(),
            len,
        ),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_list_peer_details(
    len: i32,
) -> *mut wire_cst_list_peer_details {
    let wrap = wire_cst_list_peer_details {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
            <wire_cst_peer_details>::new_with_null_ptr(),
            len,
        ),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_list_pending_sweep_balance(
    len: i32,
) -> *mut wire_cst_list_pending_sweep_balance {
    let wrap = wire_cst_list_pending_sweep_balance {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
            <wire_cst_pending_sweep_balance>::new_with_null_ptr(),
            len,
        ),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_list_prim_u_8_loose(
    len: i32,
) -> *mut wire_cst_list_prim_u_8_loose {
    let ans = wire_cst_list_prim_u_8_loose {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_list_prim_u_8_strict(
    len: i32,
) -> *mut wire_cst_list_prim_u_8_strict {
    let ans = wire_cst_list_prim_u_8_strict {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_list_public_key(
    len: i32,
) -> *mut wire_cst_list_public_key {
    let wrap = wire_cst_list_public_key {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
            <wire_cst_public_key>::new_with_null_ptr(),
            len,
        ),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
}

#[no_mangle]
pub extern "C" fn frbgen_ldk_node_cst_new_list_socket_address(
    len: i32,
) -> *mut wire_cst_list_socket_address {
    let wrap = wire_cst_list_socket_address {
        ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
            <wire_cst_socket_address>::new_with_null_ptr(),
            len,
        ),
        len,
    };
    flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_address {
    s: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_balance_details {
    total_onchain_balance_sats: u64,
    spendable_onchain_balance_sats: u64,
    total_lightning_balance_sats: u64,
    lightning_balances: *mut wire_cst_list_lightning_balance,
    pending_balances_from_channel_closures: *mut wire_cst_list_pending_sweep_balance,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_best_block {
    block_hash: *mut wire_cst_list_prim_u_8_strict,
    height: u32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_bolt_11_invoice {
    signed_raw_invoice: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_chain_data_source_config {
    tag: i32,
    kind: ChainDataSourceConfigKind,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub union ChainDataSourceConfigKind {
    Esplora: wire_cst_ChainDataSourceConfig_Esplora,
    nil__: (),
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_ChainDataSourceConfig_Esplora {
    field0: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_channel_config {
    forwarding_fee_proportional_millionths: u32,
    forwarding_fee_base_msat: u32,
    cltv_expiry_delta: u16,
    max_dust_htlc_exposure: *mut wire_cst_max_dust_htlc_exposure,
    force_close_avoidance_max_fee_satoshis: u64,
    accept_underpaying_htlcs: bool,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_channel_details {
    channel_id: wire_cst_channel_id,
    counterparty_node_id: wire_cst_public_key,
    funding_txo: *mut wire_cst_out_point,
    channel_value_sats: u64,
    unspendable_punishment_reserve: *mut u64,
    user_channel_id: wire_cst_user_channel_id,
    feerate_sat_per_1000_weight: u32,
    outbound_capacity_msat: u64,
    inbound_capacity_msat: u64,
    confirmations_required: *mut u32,
    confirmations: *mut u32,
    is_outbound: bool,
    is_channel_ready: bool,
    is_usable: bool,
    is_public: bool,
    cltv_expiry_delta: *mut u16,
    counterparty_unspendable_punishment_reserve: u64,
    counterparty_outbound_htlc_minimum_msat: *mut u64,
    counterparty_outbound_htlc_maximum_msat: *mut u64,
    counterparty_forwarding_info_fee_base_msat: *mut u32,
    counterparty_forwarding_info_fee_proportional_millionths: *mut u32,
    counterparty_forwarding_info_cltv_expiry_delta: *mut u16,
    next_outbound_htlc_limit_msat: u64,
    next_outbound_htlc_minimum_msat: u64,
    force_close_spend_delay: *mut u16,
    inbound_htlc_minimum_msat: u64,
    inbound_htlc_maximum_msat: *mut u64,
    config: wire_cst_channel_config,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_channel_id {
    data: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_closure_reason {
    tag: i32,
    kind: ClosureReasonKind,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub union ClosureReasonKind {
    CounterpartyForceClosed: wire_cst_ClosureReason_CounterpartyForceClosed,
    ProcessingError: wire_cst_ClosureReason_ProcessingError,
    nil__: (),
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_ClosureReason_CounterpartyForceClosed {
    peer_msg: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_ClosureReason_ProcessingError {
    err: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_config {
    storage_dir_path: *mut wire_cst_list_prim_u_8_strict,
    log_dir_path: *mut wire_cst_list_prim_u_8_strict,
    network: i32,
    listening_addresses: *mut wire_cst_list_socket_address,
    default_cltv_expiry_delta: u32,
    onchain_wallet_sync_interval_secs: u64,
    wallet_sync_interval_secs: u64,
    fee_rate_cache_update_interval_secs: u64,
    trusted_peers_0conf: *mut wire_cst_list_public_key,
    probing_liquidity_limit_multiplier: u64,
    log_level: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_entropy_source_config {
    tag: i32,
    kind: EntropySourceConfigKind,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub union EntropySourceConfigKind {
    SeedFile: wire_cst_EntropySourceConfig_SeedFile,
    SeedBytes: wire_cst_EntropySourceConfig_SeedBytes,
    Bip39Mnemonic: wire_cst_EntropySourceConfig_Bip39Mnemonic,
    nil__: (),
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_EntropySourceConfig_SeedFile {
    field0: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_EntropySourceConfig_SeedBytes {
    field0: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_EntropySourceConfig_Bip39Mnemonic {
    mnemonic: *mut wire_cst_mnemonic_base,
    passphrase: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_event {
    tag: i32,
    kind: EventKind,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub union EventKind {
    PaymentSuccessful: wire_cst_Event_PaymentSuccessful,
    PaymentFailed: wire_cst_Event_PaymentFailed,
    PaymentReceived: wire_cst_Event_PaymentReceived,
    ChannelPending: wire_cst_Event_ChannelPending,
    ChannelReady: wire_cst_Event_ChannelReady,
    ChannelClosed: wire_cst_Event_ChannelClosed,
    nil__: (),
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_Event_PaymentSuccessful {
    payment_hash: *mut wire_cst_payment_hash,
    fee_paid_msat: *mut u64,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_Event_PaymentFailed {
    payment_hash: *mut wire_cst_payment_hash,
    reason: *mut i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_Event_PaymentReceived {
    payment_hash: *mut wire_cst_payment_hash,
    amount_msat: u64,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_Event_ChannelPending {
    channel_id: *mut wire_cst_channel_id,
    user_channel_id: *mut wire_cst_user_channel_id,
    former_temporary_channel_id: *mut wire_cst_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
    funding_txo: *mut wire_cst_out_point,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_Event_ChannelReady {
    channel_id: *mut wire_cst_channel_id,
    user_channel_id: *mut wire_cst_user_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_Event_ChannelClosed {
    channel_id: *mut wire_cst_channel_id,
    user_channel_id: *mut wire_cst_user_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
    reason: *mut wire_cst_closure_reason,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_gossip_source_config {
    tag: i32,
    kind: GossipSourceConfigKind,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub union GossipSourceConfigKind {
    RapidGossipSync: wire_cst_GossipSourceConfig_RapidGossipSync,
    nil__: (),
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_GossipSourceConfig_RapidGossipSync {
    field0: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_lightning_balance {
    tag: i32,
    kind: LightningBalanceKind,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub union LightningBalanceKind {
    ClaimableOnChannelClose: wire_cst_LightningBalance_ClaimableOnChannelClose,
    ClaimableAwaitingConfirmations: wire_cst_LightningBalance_ClaimableAwaitingConfirmations,
    ContentiousClaimable: wire_cst_LightningBalance_ContentiousClaimable,
    MaybeTimeoutClaimableHTLC: wire_cst_LightningBalance_MaybeTimeoutClaimableHTLC,
    MaybePreimageClaimableHTLC: wire_cst_LightningBalance_MaybePreimageClaimableHTLC,
    CounterpartyRevokedOutputClaimable:
        wire_cst_LightningBalance_CounterpartyRevokedOutputClaimable,
    nil__: (),
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_LightningBalance_ClaimableOnChannelClose {
    channel_id: *mut wire_cst_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
    amount_satoshis: u64,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_LightningBalance_ClaimableAwaitingConfirmations {
    channel_id: *mut wire_cst_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
    amount_satoshis: u64,
    confirmation_height: u32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_LightningBalance_ContentiousClaimable {
    channel_id: *mut wire_cst_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
    amount_satoshis: u64,
    timeout_height: u32,
    payment_hash: *mut wire_cst_payment_hash,
    payment_preimage: *mut wire_cst_payment_preimage,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_LightningBalance_MaybeTimeoutClaimableHTLC {
    channel_id: *mut wire_cst_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
    amount_satoshis: u64,
    claimable_height: u32,
    payment_hash: *mut wire_cst_payment_hash,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_LightningBalance_MaybePreimageClaimableHTLC {
    channel_id: *mut wire_cst_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
    amount_satoshis: u64,
    expiry_height: u32,
    payment_hash: *mut wire_cst_payment_hash,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_LightningBalance_CounterpartyRevokedOutputClaimable {
    channel_id: *mut wire_cst_channel_id,
    counterparty_node_id: *mut wire_cst_public_key,
    amount_satoshis: u64,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_liquidity_source_config {
    lsps2_service: wire_cst_record_socket_address_public_key_opt_string,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_list_channel_details {
    ptr: *mut wire_cst_channel_details,
    len: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_list_lightning_balance {
    ptr: *mut wire_cst_lightning_balance,
    len: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_list_payment_details {
    ptr: *mut wire_cst_payment_details,
    len: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_list_peer_details {
    ptr: *mut wire_cst_peer_details,
    len: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_list_pending_sweep_balance {
    ptr: *mut wire_cst_pending_sweep_balance,
    len: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_list_prim_u_8_loose {
    ptr: *mut u8,
    len: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_list_prim_u_8_strict {
    ptr: *mut u8,
    len: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_list_public_key {
    ptr: *mut wire_cst_public_key,
    len: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_list_socket_address {
    ptr: *mut wire_cst_socket_address,
    len: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_max_dust_htlc_exposure {
    tag: i32,
    kind: MaxDustHTLCExposureKind,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub union MaxDustHTLCExposureKind {
    FixedLimitMsat: wire_cst_MaxDustHTLCExposure_FixedLimitMsat,
    FeeRateMultiplier: wire_cst_MaxDustHTLCExposure_FeeRateMultiplier,
    nil__: (),
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_MaxDustHTLCExposure_FixedLimitMsat {
    field0: u64,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_MaxDustHTLCExposure_FeeRateMultiplier {
    field0: u64,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_mnemonic_base {
    seed_phrase: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_node_base {
    ptr: usize,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_node_status {
    is_running: bool,
    is_listening: bool,
    current_best_block: wire_cst_best_block,
    latest_wallet_sync_timestamp: *mut u64,
    latest_onchain_wallet_sync_timestamp: *mut u64,
    latest_fee_rate_cache_update_timestamp: *mut u64,
    latest_rgs_snapshot_timestamp: *mut u64,
    latest_node_announcement_broadcast_timestamp: *mut u64,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_out_point {
    txid: wire_cst_txid,
    vout: u32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_payment_details {
    hash: wire_cst_payment_hash,
    preimage: *mut wire_cst_payment_preimage,
    secret: *mut wire_cst_payment_secret,
    amount_msat: *mut u64,
    direction: i32,
    status: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_payment_hash {
    data: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_payment_preimage {
    data: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_payment_secret {
    data: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_peer_details {
    node_id: wire_cst_public_key,
    address: wire_cst_socket_address,
    is_connected: bool,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_pending_sweep_balance {
    tag: i32,
    kind: PendingSweepBalanceKind,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub union PendingSweepBalanceKind {
    PendingBroadcast: wire_cst_PendingSweepBalance_PendingBroadcast,
    BroadcastAwaitingConfirmation: wire_cst_PendingSweepBalance_BroadcastAwaitingConfirmation,
    AwaitingThresholdConfirmations: wire_cst_PendingSweepBalance_AwaitingThresholdConfirmations,
    nil__: (),
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_PendingSweepBalance_PendingBroadcast {
    channel_id: *mut wire_cst_channel_id,
    amount_satoshis: u64,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_PendingSweepBalance_BroadcastAwaitingConfirmation {
    channel_id: *mut wire_cst_channel_id,
    latest_broadcast_height: u32,
    latest_spending_txid: *mut wire_cst_txid,
    amount_satoshis: u64,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_PendingSweepBalance_AwaitingThresholdConfirmations {
    channel_id: *mut wire_cst_channel_id,
    latest_spending_txid: *mut wire_cst_txid,
    confirmation_hash: *mut wire_cst_list_prim_u_8_strict,
    confirmation_height: u32,
    amount_satoshis: u64,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_public_key {
    hex_code: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_record_socket_address_public_key_opt_string {
    field0: wire_cst_socket_address,
    field1: wire_cst_public_key,
    field2: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_socket_address {
    tag: i32,
    kind: SocketAddressKind,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub union SocketAddressKind {
    TcpIpV4: wire_cst_SocketAddress_TcpIpV4,
    TcpIpV6: wire_cst_SocketAddress_TcpIpV6,
    OnionV2: wire_cst_SocketAddress_OnionV2,
    OnionV3: wire_cst_SocketAddress_OnionV3,
    Hostname: wire_cst_SocketAddress_Hostname,
    nil__: (),
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_SocketAddress_TcpIpV4 {
    addr: *mut wire_cst_list_prim_u_8_strict,
    port: u16,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_SocketAddress_TcpIpV6 {
    addr: *mut wire_cst_list_prim_u_8_strict,
    port: u16,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_SocketAddress_OnionV2 {
    field0: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_SocketAddress_OnionV3 {
    ed25519_pubkey: *mut wire_cst_list_prim_u_8_strict,
    checksum: u16,
    version: u8,
    port: u16,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_SocketAddress_Hostname {
    addr: *mut wire_cst_list_prim_u_8_strict,
    port: u16,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_txid {
    hash: *mut wire_cst_list_prim_u_8_strict,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct wire_cst_user_channel_id {
    data: *mut wire_cst_list_prim_u_8_strict,
}
